### ISSUE TITLE
Creating a container failing with lxd 2.5

### ISSUE THREAD

**Issue by uSpike** [lxc/pylxd#197]
Executing the example to create a container:
```
import pylxd
import logging

logging.basicConfig(level=logging.DEBUG)

client = pylxd.Client()
config = {'name': 'test-container', 'source': {'type': 'image', 'image': 'ubuntu/trusty'}}
ctr = client.containers.create(config, wait=True)
```

```
DEBUG:requests.packages.urllib3.connectionpool:"GET /1.0 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"POST /1.0/containers HTTP/1.1" 400 118
Traceback (most recent call last):
  File "lxd_test.py", line 10, in <module>
    ctr = client.containers.create(config, wait=True)
  File "/home/xxx/venv2/local/lib/python2.7/site-packages/pylxd/models/container.py", line 115, in create
    response = client.api.containers.post(json=config)
  File "/home/xxx/venv2/local/lib/python2.7/site-packages/pylxd/client.py", line 109, in post
    self._assert_response(response, allowed_status_codes=(200, 201, 202))
  File "/home/xxx/venv2/local/lib/python2.7/site-packages/pylxd/client.py", line 67, in _assert_response
    raise exceptions.LXDAPIException(response)
pylxd.exceptions.LXDAPIException: Must specify one of alias, fingerprint or properties for init from image
```

```
 $ pip list
...
pylxd (2.1.2)
requests (2.11.1)
requests-unixsocket (0.1.5)
 $ lxd --version
2.5
```

**Comment by uSpike** [comment]
Looks like it's an error in the docs, the [api spec](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-1) shows that it should be `'source': {'type': 'image', 'alias': 'ubuntu/trusty'}}`

**Comment by uSpike** [comment]
This is my stupid, sorry for the noise.

**Comment by matheo** [comment]
@uSpike let me ask: `source` didn't work? which code worked? thanks

**Comment by uSpike** [comment]
@matheo see https://github.com/lxc/lxd/blob/master/doc/rest-api.md#post-1

The default image server is of course the client server (local).  We didn't have an aliases set for our images, so this was causing me quite the headache.  I improved my code by linking to upstream servers by referencing https://github.com/lxc/lxd/blob/b0e3b4cea6b085581e4b36b8af5f633f4c6ec673/config.go#L59.

Something like:

```
    config = {
        ...
        "source": {
               "type": "image"
               "mode": "pull",
               "server": "https://cloud-images.ubuntu.com/releases",
               "protocol": "simplestreams"
               "alias": "16.04"
        }
    }
```
