### ISSUE TITLE
Stopping ephermal container with wait=True throws

### ISSUE THREAD

**Issue by om26er** [lxc/pylxd#221]
Using pylxd 2.2.2

If you stop an ephermal container it raises.

```
>>> c.stop(wait=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pylxd/models/container.py", line 180, in stop
    wait=wait)
  File "/usr/local/lib/python3.5/dist-packages/pylxd/models/container.py", line 161, in _set_state
    self.sync()
  File "/usr/local/lib/python3.5/dist-packages/pylxd/models/_model.py", line 151, in sync
    response = self.api.get()
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 103, in get
    self._assert_response(response, stream=kwargs.get('stream', False))
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 68, in _assert_response
    raise exceptions.NotFound(response)
pylxd.exceptions.NotFound: not found
```

**Comment by om26er** [comment]
Fix here: https://github.com/lxc/pylxd/pull/222
