### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by ChrisMacNaughton** [lxc/pylxd#235]
Nearly half of the test suite (`tox`) are failing with

```
======================================================================
ERROR: A profile is updated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/media/projects/lxd/pylxd/pylxd/tests/testing.py", line 28, in setUp
    mock_services.start_http_mock()
  File "/mnt/media/projects/lxd/pylxd/.tox/py27/local/lib/python2.7/site-packages/mock_services/helpers.py", line 15, in start_http_mock
    if not http_mock.is_started():
  File "/mnt/media/projects/lxd/pylxd/.tox/py27/local/lib/python2.7/site-packages/mock_services/http_mock.py", line 28, in is_started
    return self._real_send
  File "/mnt/media/projects/lxd/pylxd/.tox/py27/local/lib/python2.7/site-packages/requests_mock/mocker.py", line 132, in __getattr__
    raise AttributeError(name)
AttributeError: _real_send
```

**Comment by ChrisMacNaughton** [comment]
maybe resolved in #233

**Comment by ajkavanagh** [comment]
Is this resolved now?

**Comment by ChrisMacNaughton** [comment]
Indeed it is
