### ISSUE TITLE
pip install pylxd fails

### ISSUE THREAD

**Issue by johnsom** [lxc/pylxd#275]
Attempting a pip install on a fresh xenial host for an OpenStack devstack fails with the below error.
Checking out master git (71e1029ccb0f934c75d97740203bc58d70e760a2) also fails to install via "pip install ."
Error below:

root@novalxd:~/devstack# pip install pylxd
The directory '/opt/stack/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/opt/stack/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pylxd
  Downloading pylxd-2.2.4.tar.gz (66kB)
    100% |████████████████████████████████| 71kB 1.7MB/s
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-74vLsB/pylxd/.eggs/requests_unixsocket-0.1.5-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/dist-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/usr/local/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 46, in <module>
        from sphinx.util.websupport import is_commentable
      File "/usr/local/lib/python2.7/dist-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/usr/lib/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/local/lib/python2.7/dist-packages/typing.py", line 1265, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    error in setup command: Error parsing /tmp/pip-build-74vLsB/pylxd/setup.cfg: TypeError: super() argument 1 must be type, not None

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-74vLsB/pylxd/

**Comment by ajkavanagh** [comment]
I think that you've hit this bug: https://github.com/sphinx-doc/sphinx/issues/3976

It seems to be a problem/incompatibility between setuptools and sphinx.

When I install from `master` on on a clean 16.04.3 using:

```bash
$ sudo apt update
$ sudo apt install python-pip
$ git clone https://github.com/lxc/pylxd.git
$ cd pylxd/
$ sudo pip install .
```

it works.  So, there's something else weird going on.

The exact version of ubuntu I used was: ubuntu-xenial-16.04-amd64-server-20180126-disk1.img from the ubuntu image daily archive.

**Comment by johnsom** [comment]
Yes, I agree, this is likely the reported sphinx bug.
This host had started the devstack setup (mentioned above), so I suspect that is where the sphinx version came into the system.

**Comment by ajkavanagh** [comment]
Yeah, when I install on devstack, I always install pylxd first, and then the devstack setup doesn't try and install it again.
