### ISSUE TITLE
Problem with integration testing

### ISSUE THREAD

**Issue by ppkt** [lxc/pylxd#302]
Hi,
I started implementing API for Network - I created few unit tests and everything was working quite good but when I started working on integration tests I'm getting 'not implemented' exception when I'm trying to create new network:
```
(integration) root@lxd-test:/opt/pylxd# python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylxd import Client
>>> c = Client()
>>> c.networks.all()
[<pylxd.models.network.Network object at 0x7f49fa1e8840>, <pylxd.models.network.Network object at 0x7f49fa1e88b8>, <pylxd.models.network.Network object at 0x7f49fa1e8930>]
>>> c.networks.create(name='test')
<pylxd.client._APINode object at 0x7f49fa5454a8>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pylxd/pylxd/models/network.py", line 67, in create
    client.api.networks.post(json=network)
  File "/opt/pylxd/pylxd/client.py", line 157, in post
    self._assert_response(response, allowed_status_codes=(200, 201, 202))
  File "/opt/pylxd/pylxd/client.py", line 104, in _assert_response
    raise exceptions.LXDAPIException(response)
pylxd.exceptions.LXDAPIException: not implemented
```

But when I run the same code on my local machine (not in container) everything is working correctly:

```
$ python3
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylxd import Client
>>> c = Client()
>>> net = c.networks.create(name='test')
<pylxd.client._APINode object at 0x7fd87d76ee48>
/home/ppkt/workspace/pylxd/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "status" on instance of "Network"
  key, self.__class__.__name__
/home/ppkt/workspace/pylxd/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "locations" on instance of "Network"
  key, self.__class__.__name__
>>> net.marshall()
{'name': 'test', 'description': '', 'type': 'bridge', 'config': {'ipv4.address': '10.71.150.1/24', 'ipv4.nat': 'true', 'ipv6.address': 'fd42:b17:be25:6bdf::1/64', 'ipv6.nat': 'true'}, 'managed': True}
>>> net.delete()
>>> c.networks.get('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ppkt/workspace/pylxd/pylxd/models/network.py", line 38, in get
    response = client.api.networks[name].get()
  File "/home/ppkt/workspace/pylxd/pylxd/client.py", line 148, in get
    is_api=is_api)
  File "/home/ppkt/workspace/pylxd/pylxd/client.py", line 103, in _assert_response
    raise exceptions.NotFound(response)
pylxd.exceptions.NotFound: not found
>>> 
```
I also ran grep on container to check where this exception is raised but also without success:
```
root@lxd-test:/opt/pylxd/pylxd# grep -R 'not implemented'
deprecated/profiles.py:        '''Update the LXD profile (not implemented)'''
models/storage_pool.py:        raise NotImplementedError('save is not implemented')
models/storage_pool.py:        raise NotImplementedError('delete is not implemented')
Binary file models/__pycache__/storage_pool.cpython-35.pyc matches
tests/models/test_network.py:        """delete is not implemented in networks."""
tests/models/test_storage.py:        """delete is not implemented in storage_pools."""
tests/models/test_storage.py:        """save is not implemented in storage_pools."""
```

I guess this bug is quite easy to fix but I couldn't find the solution for a while.

**Comment by ajkavanagh** [comment]
Hi @ppkt, I suspect that that exception is coming from lxd itself. I reckon we could make that clearer in the exception that `pylxd` raises, so it's clear where it's being generated.  However, to try to help with your issue, could you have a look at the versions of lxc, lxd, and pyxld in the two testing environments?

**Comment by ppkt** [comment]
Thanks for quick responses - yes, it's quite possible - I'm using `run_integration_tests` script to run tests and apparently in Ubuntu 16.04 there is older version of LXD. I'll check this tomorrow and I'll let you know.

**Comment by ppkt** [comment]
@ajkavanagh @stgraber you were right, on 16.04 LXD is in version 2.0.11. I bumped it to 17.10 and problem disappeared (LXD 2.18). Thank you for your time :)
