### ISSUE TITLE
container.files.get does not work with read only file system (Ubuntu core)

### ISSUE THREAD

**Issue by shuhaowu** [lxc/pylxd#305]
Start a ubuntu core (16) lxd container, try to access a file from it via:

```
>>> import pylxd
>>> client = pylxd.Client()
>>> container = client.containers.get("ubuntu-core-test")
>>> container.files.get("/etc/os-release")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shuhao/.local/lib/python3.5/site-packages/pylxd/models/container.py", line 141, in get
    .files.get(params={'path': filepath}))
  File "/home/shuhao/.local/lib/python3.5/site-packages/pylxd/client.py", line 125, in get
    self._assert_response(response, stream=kwargs.get('stream', False))
  File "/home/shuhao/.local/lib/python3.5/site-packages/pylxd/client.py", line 91, in _assert_response
    raise exceptions.LXDAPIException(response)
pylxd.exceptions.LXDAPIException: open: Read-only file system
```

**Comment by shuhaowu** [comment]
Actually this seems like an upstream issue:

```
$ lxc file pull ubuntu-core-test/etc/os-release .                                                                           
error: open: Read-only file system
```
