### ISSUE TITLE
Test failures on Ubuntu 14.04

### ISSUE THREAD

**Issue by javacruft** [lxc/pylxd#42]
```
==============================
Failed 2 tests - output below:
==============================

pylxd.tests.test_connection.LXDInitConnectionTest.test_https_connection
-----------------------------------------------------------------------

Captured traceback:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "/��PKGBUILDDIR��/pylxd/tests/test_connection.py", line 48, in test_https_connection
        conn.connect()
      File "/��PKGBUILDDIR��/pylxd/connection.py", line 57, in connect
        ssl_version=ssl.PROTOCOL_TLSv1_2)
    AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
    
pylxd.tests.test_connection.LXDInitConnectionTest.test_https_proxy_connection
-----------------------------------------------------------------------------
Captured traceback:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "/��PKGBUILDDIR��/pylxd/tests/test_connection.py", line 66, in test_https_proxy_connection
        conn.connect()
      File "/��PKGBUILDDIR��/pylxd/connection.py", line 57, in connect
        ssl_version=ssl.PROTOCOL_TLSv1_2)
    AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
```

**Comment by javacruft** [comment]
Updated in repo; closing issue.
