### ISSUE TITLE
pylxd at nested container

### ISSUE THREAD

**Issue by tkasidakis** [lxc/pylxd#465]
Hello. I have a LXD container with name Server1 . Inside the container i have installed pylxd.

When i am trying to execute for example a Python script which prints the available images inside the Server1, it returns an empty list. However, i have images available. Generally it seems not to working. I tried also to create a container inside the Server1 container with pylxd and the operation failed with exception "no such object".

Any help @ajkavanagh with that ?

**Comment by albertodonato** [comment]
Could you please share your sample script?

**Comment by tkasidakis** [comment]
@albertodonato 

`from pylxd import Client

lxd=Client()

images  = lxd.images.all() # take the local available images as Python objects
ServerServicesImagesNames = [] # a list with the Images  names
if(len(images)!=0):
	for i in range(len(images)):
		ServerServicesImagesNames.append(images[i].aliases[0]["name"])
	#endfor
#endif

print(ServerServicesImagesNames)`

**Comment by albertodonato** [comment]
could you pelase attach the output of `lxc remote list`?

**Comment by tkasidakis** [comment]
```
root@Server1:~# lxc remote list
+-----------------+------------------------------------------+---------------+-----------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | AUTH TYPE | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+-----------+--------+--------+
| images          | https://images.linuxcontainers.org       | simplestreams |           | YES    | NO     |
+-----------------+------------------------------------------+---------------+-----------+--------+--------+
| local (default) | unix://                                  | lxd           | tls       | NO     | YES    |
+-----------------+------------------------------------------+---------------+-----------+--------+--------+
| ubuntu          | https://cloud-images.ubuntu.com/releases | simplestreams |           | YES    | YES    |
+-----------------+------------------------------------------+---------------+-----------+--------+--------+
| ubuntu-daily    | https://cloud-images.ubuntu.com/daily    | simplestreams |           | YES    | YES    |
+-----------------+------------------------------------------+---------------+-----------+--------+--------+
```

**Comment by albertodonato** [comment]
from your script, could you add `print(lxd.api._api_endpoint)` to your script, and report what it shows there?

Also is `LXD_DIR`  by chance set in the shell where you run the script?

**Comment by tkasidakis** [comment]
```
root@Server1:~# python3 sample_script.py 
[]
http+unix://%2Fvar%2Fsnap%2Flxd%2Fcommon%2Flxd%2Funix.socket/1.0
```
@albertodonato 
Can you please explain what do you mean with the LXD_DIR ?

**Comment by albertodonato** [comment]
I meant whether `echo $LXD_DIR` returns anything from the shell where you run the script.

But given the previous output it doesn't really matter

**Comment by tkasidakis** [comment]
@albertodonato  So what is going on ?

**Comment by albertodonato** [comment]
Not sure yet, could you please confirm which version of pylxd are you using?

**Comment by tkasidakis** [comment]
I believe the latest one using pip3 install pylxd

**Comment by tkasidakis** [comment]
@albertodonato 
```
root@Server1:~# pip3 install pylxd
Requirement already satisfied: pylxd in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: requests-toolbelt>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from pylxd)
Requirement already satisfied: requests-unixsocket>=0.1.5 in /usr/lib/python3/dist-packages (from pylxd)
Requirement already satisfied: cryptography!=1.3.0,>=1.0 in /usr/lib/python3/dist-packages (from pylxd)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.6/dist-packages (from pylxd)
Requirement already satisfied: ws4py!=0.3.5,>=0.3.4 in /usr/local/lib/python3.6/dist-packages (from pylxd)
Requirement already satisfied: python-dateutil>=2.4.2 in /usr/local/lib/python3.6/dist-packages (from pylxd)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from pylxd)
Requirement already satisfied: pbr>=1.6 in /usr/local/lib/python3.6/dist-packages (from pylxd)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.20.0->pylxd)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.20.0->pylxd)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.20.0->pylxd)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.20.0->pylxd)
```

**Comment by albertodonato** [comment]
do you have both the lxd snap and deb installed?
could you paste the output for `snap info lxd` and `dpkg -l | grep lxd` ?

**Comment by tkasidakis** [comment]
```
root@Server1:~# snap info lxd
name:      lxd
summary:   System container manager and API
publisher: Canonical✓
store-url: https://snapcraft.io/lxd
contact:   https://github.com/lxc/lxd/issues
license:   unset
description: |
  **LXD is a system container manager**
  
  With LXD you can run hundreds of containers of a variety of Linux
  distributions, apply resource limits, pass in directories, USB devices
  or GPUs and setup any network and storage you want.
  
  LXD containers are lightweight, secure by default and a great
  alternative to running Linux virtual machines.
  
  
  **Run any Linux distribution you want**
  
  Pre-made images are available for Ubuntu, Alpine Linux, ArchLinux,
  CentOS, Debian, Fedora, Gentoo, OpenSUSE and more.
  
  A full list of available images can be found here: https://images.linuxcontainers.org
  
  Can't find the distribution you want? It's easy to make your own images too, either using our
  `distrobuilder` tool or by assembling your own image tarball by hand.
  
  
  **Containers at scale**
  
  LXD is network aware and all interactions go through a simple REST API,
  making it possible to remotely interact with containers on remote
  systems, copying and moving them as you wish.
  
  Want to go big? LXD also has built-in clustering support,
  letting you turn dozens of servers into one big LXD server.
  
  
  **Configuration options**
  
  Supported options for the LXD snap (`snap set lxd KEY=VALUE`):
     - ceph.builtin: Use snap-specific ceph configuration [default=false]
     - criu.enable: Enable experimental live-migration support [default=false]
     - daemon.debug: Increases logging to debug level [default=false]
     - daemon.group: Group of users that can interact with LXD [default=lxd]
     - daemon.preseed: A YAML configuration to feed `lxd init` on initial start
     - lxcfs.pidfd: Start per-container process tracking [default=false]
     - lxcfs.loadavg: Start tracking per-container load average [default=false]
     - lxcfs.cfs: Consider CPU shares for CPU usage [default=false]
     - openvswitch.builtin: Run a snap-specific OVS daemon [default=false]
     - shiftfs.enable: Enable shiftfs support [default=auto]
  
  Documentation: https://lxd.readthedocs.io
commands:
  - lxd.benchmark
  - lxd.buginfo
  - lxd.check-kernel
  - lxd.lxc
  - lxd.lxc-to-lxd
  - lxd
  - lxd.migrate
services:
  lxd.activate: oneshot, enabled, inactive
  lxd.daemon:   simple, enabled, active
snap-id:      J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:     latest/stable
refresh-date: today at 12:59 UTC
channels:
  latest/stable:    4.11        2021-02-12 (19389) 74MB -
  latest/candidate: 4.11        2021-02-12 (19389) 74MB -
  latest/beta:      ↑                                   
  latest/edge:      git-edcf89d 2021-02-11 (19380) 74MB -
  4.11/stable:      4.11        2021-02-12 (19389) 74MB -
  4.11/candidate:   4.11        2021-02-12 (19389) 74MB -
  4.11/beta:        ↑                                   
  4.11/edge:        ↑                                   
  4.10/stable:      4.10        2021-01-29 (19164) 74MB -
  4.10/candidate:   4.10        2021-01-29 (19164) 74MB -
  4.10/beta:        ↑                                   
  4.10/edge:        ↑                                   
  4.9/stable:       4.9         2020-12-18 (18772) 74MB -
  4.9/candidate:    4.9         2020-12-18 (18772) 74MB -
  4.9/beta:         ↑                                   
  4.9/edge:         ↑                                   
  4.8/stable:       4.8         2020-12-08 (18546) 74MB -
  4.8/candidate:    4.8         2020-12-07 (18546) 74MB -
  4.8/beta:         ↑                                   
  4.8/edge:         ↑                                   
  4.7/stable:       4.7         2020-11-12 (18251) 72MB -
  4.7/candidate:    4.7         2020-11-12 (18251) 72MB -
  4.7/beta:         ↑                                   
  4.7/edge:         ↑                                   
  4.0/stable:       4.0.5       2021-02-01 (19188) 73MB -
  4.0/candidate:    4.0.5       2021-02-12 (19398) 73MB -
  4.0/beta:         ↑                                   
  4.0/edge:         git-a71648c 2021-02-12 (19404) 73MB -
  3.0/stable:       3.0.4       2019-10-10 (11348) 55MB -
  3.0/candidate:    3.0.4       2019-10-10 (11348) 55MB -
  3.0/beta:         ↑                                   
  3.0/edge:         git-81b81b9 2019-10-10 (11362) 55MB -
  2.0/stable:       2.0.12      2020-08-18 (16879) 38MB -
  2.0/candidate:    2.0.12      2020-08-17 (16879) 38MB -
  2.0/beta:         ↑                                   
  2.0/edge:         git-82c7d62 2020-08-17 (16867) 39MB -
installed:          4.11                   (19389) 74MB -
```
root@Server1:~# dpkg -l | grep lxd
ii  lxd                            3.0.3-0ubuntu1~18.04.1              amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                     3.0.3-0ubuntu1~18.04.1              amd64        Container hypervisor based on LXC - client


```
shit . . . .
```

**Comment by albertodonato** [comment]
ok, so you're likely using the `lxc` CLI from the deb (you can verify with `which lxc`) which connects to the deb-based LXD, while pylxd is connecting to the unix socket for the snap-based LXD.

if you create the pylxd client as `lxd = Client(endpoint="/var/lib/lxd/unix.socket")` you should get the same result as the CLI.

pylxd defaults to the snap path as that's the preferred method to install LXD

**Comment by tkasidakis** [comment]
```
root@Server1:~# python3 sample_script.py 
Traceback (most recent call last):
  File "sample_script.py", line 3, in <module>
    lxd=Client(endpoint="/var/lib/lxd/unix.socket")
  File "/usr/local/lib/python3.6/dist-packages/pylxd/client.py", line 318, in __init__
    response = self.api.get()
  File "/usr/local/lib/python3.6/dist-packages/pylxd/client.py", line 158, in get
    response = self.session.get(self._api_endpoint, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/var/lib/lxd/unix.socket/1.0': No schema supplied. Perhaps you meant http:///var/lib/lxd/unix.socket/1.0?
```
I tried also  http:///var/lib/lxd/unix.socket/1.0 but didn't work
```

root@Server1:~# which lxc
/usr/bin/lxc

```

**Comment by albertodonato** [comment]
oh now you're hitting https://github.com/lxc/pylxd/pull/371

as a workaround I think you can set `LXD_DIR=/var/lib/lxd` as an environ variable before calling your script.

I'll take a look at landing the fix for that issue too

**Comment by tkasidakis** [comment]
@albertodonato 

Can you help me with how setting this environ variable ?

**Comment by tkasidakis** [comment]
```
root@Server1:~# export LXD_DIR=/var/lib/lxd
root@Server1:~# python3 sample_script.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pylxd/client.py", line 318, in __init__
    response = self.api.get()
  File "/usr/local/lib/python3.6/dist-packages/pylxd/client.py", line 158, in get
    response = self.session.get(self._api_endpoint, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 393, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'http:///var/lib/lxd/unix.socket/1.0/1.0': No host supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample_script.py", line 3, in <module>
    lxd=Client(endpoint="http:///var/lib/lxd/unix.socket/1.0")
  File "/usr/local/lib/python3.6/dist-packages/pylxd/client.py", line 325, in __init__
    raise exceptions.ClientConnectionFailed(str(e))
pylxd.exceptions.ClientConnectionFailed: Invalid URL 'http:///var/lib/lxd/unix.socket/1.0/1.0': No host supplied
```

**Comment by tkasidakis** [comment]
```
root@Server1:~# export LXD_DIR=/var/lib/lxd
root@Server1:~# python3 sample_script.py
Traceback (most recent call last):
  File "sample_script.py", line 3, in <module>
    lxd=Client(endpoint="/var/lib/lxd/unix.socket")
  File "/usr/local/lib/python3.6/dist-packages/pylxd/client.py", line 318, in __init__
    response = self.api.get()
  File "/usr/local/lib/python3.6/dist-packages/pylxd/client.py", line 158, in get
    response = self.session.get(self._api_endpoint, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/var/lib/lxd/unix.socket/1.0': No schema supplied. Perhaps you meant http:///var/lib/lxd/unix.socket/1.0?
```

@albertodonato

**Comment by tkasidakis** [comment]
If i create a container which has only snap lxd inside, is this going to fix the above issue ?

**Comment by albertodonato** [comment]
yes. you can also uninstall the lxc/lxd packages in the container
