### ISSUE TITLE
Connection refused error when using UNIX socket

### ISSUE THREAD

**Issue by tomers** [lxc/pylxd#525]
```
# In the host, I have the relevant permissions to the Unix socket:

ubuntu@ip-xxx-xx-xx-xx:~$ ls -l /var/snap/lxd/common/lxd/unix.socket
srw-rw---- 1 root lxd 0 Nov 28 04:12 /var/snap/lxd/common/lxd/unix.socket
ubuntu@ip-xxx-xx-xx-xx:~$ id
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),117(netdev),30001(lxd)

# I am able to use pylxd regularly:

ubuntu@ip-xxx-xx-xx-xx:~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
>>> import pylxd
>>> pylxd.__version__
'2.3.1'
>>> LXD_CLIENT = pylxd.Client()
>>> container = LXD_CLIENT.containers.get('zero')
>>> container.execute(['pwd'])
_InstanceExecuteResult(exit_code=0, stdout='/root\n', stderr='')
```

However, this doesn't work well in a docker. I map the host's socket to the docker:
```
    volumes:
      - "/var/snap/lxd/common/lxd/unix.socket:/var/snap/lxd/common/lxd/unix.socket"
```
Everything works, until in some occasions (probably lxd service restart), I am unable to connect anymore:
```
# In the docker, I have proper permissions:

ubuntu@ip-xxx-xx-xx-xx:~$ sudo docker exec -it tweety bash
www-data@ip-xxx-xx-xx-xx:/usr/src/app$ ls -l /var/snap/lxd/common/lxd/unix.socket
srw-rw---- 0 root lxd 0 Nov 27 21:27 /var/snap/lxd/common/lxd/unix.socket
www-data@ip-xxx-xx-xx-xx:/usr/src/app$ id
uid=33(www-data) gid=33(www-data) groups=33(www-data),30001(lxd)

# The issue is that after a while, I get errors when trying to create a pylxd client:

www-data@ip-xxx-xx-xx-xx:/usr/src/app$ python3
Python 3.8.15 (default, Nov 15 2022, 22:12:54) 
[GCC 10.2.1 20210110] on linux
>>> import pylxd
>>> pylxd.__version__
'2.3.1'
>>> LXD_CLIENT = pylxd.Client()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/requests_unixsocket/adapters.py", line 41, in connect
    sock.connect(socket_path)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/requests_unixsocket/adapters.py", line 41, in connect
    sock.connect(socket_path)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pylxd/client.py", line 383, in __init__
    response = self.api.get()
  File "/usr/local/lib/python3.8/site-packages/pylxd/client.py", line 192, in get
    response = self.session.get(self._api_endpoint, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pylxd/client.py", line 392, in __init__
    raise exceptions.ClientConnectionFailed(str(e))
pylxd.exceptions.ClientConnectionFailed: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
```

Any idea how to resolve this?

**Comment by tomers** [comment]
We suspect that following a LXD service update (possibly due to `snap`'s notorious auto refresh). A new UDS socket was created, so the one mounted to our container got invalidated.
