### ISSUE TITLE
Cannot import pylxd from terminal

### ISSUE THREAD

**Issue by alexk307** [lxc/pylxd#83]
I installed pylxd using `pip install pylxd` and when I try to load it in the terminal I get...

```
>>> import pylxd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akahan/Work/containers_js/env/lib/python2.7/site-packages/pylxd/__init__.py", line 19, in <module>
    from pylxd.deprecated import api  # NOQA
  File "/Users/akahan/Work/containers_js/env/lib/python2.7/site-packages/pylxd/deprecated/api.py", line 17, in <module>
    from pylxd.deprecated import certificate
  File "/Users/akahan/Work/containers_js/env/lib/python2.7/site-packages/pylxd/deprecated/certificate.py", line 17, in <module>
    from pylxd.deprecated import base
  File "/Users/akahan/Work/containers_js/env/lib/python2.7/site-packages/pylxd/deprecated/base.py", line 16, in <module>
    from pylxd.deprecated import connection
  File "/Users/akahan/Work/containers_js/env/lib/python2.7/site-packages/pylxd/deprecated/connection.py", line 46, in <module>
    DEFAULT_TLS_VERSION = OpenSSL.SSL.TLSv1_2_METHOD
NameError: name 'OpenSSL' is not defined
>>> import OpenSSL
>>> OpenSSL.SSL.TLSv1_2_METHOD
6
```

Not sure what's going on here and why it's trying to import code from a path with `deprecated` in it? Are there other deps that are needed to install this?

**Comment by alexk307** [comment]
Ran using python3 and it seemed to work fine. Is this lib compatible with python 2.7?

**Comment by zulcss** [comment]
Are you trying use pylxd on trusty?

**Comment by alexk307** [comment]
Yes, is that not supported?

**Comment by rockstar** [comment]
I _think_ this is fixed in #85, as a drive-by change. I tested on multiple platforms, which uncovered some issues in the logic of two if statements.

**Comment by alexk307** [comment]
OK I'll try that @rockstar, thanks

**Comment by alexk307** [comment]
@rockstar getting a new error when I try the latest version on a fresh env...


```
Python 2.7.10 (default, Oct 23 2015, 18:05:06)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylxd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pylxd/__init__.py", line 15, in <module>
    import pbr.version
ImportError: No module named pbr.version
```

**Comment by jpic** [comment]
Did you try installing pbr ?

**Comment by alexk307** [comment]
Sorry, I installed using setup.py which usually has a list or reqs, but in this case it does not install them. Thanks.

**Comment by jpic** [comment]
Yeah pbr powers setup.py so you need pbr prior to using setup.py. pbr is a bit hard to get started with, but it's really good, all openstack python packages use it, it does a lot of awesome stuff ootb such as hash-based version numbers.
