### ISSUE TITLE
Issue with autodoc module on hosted documentation

### ISSUE THREAD

**Issue by jpic** [lxc/pylxd#99]
Currently on the hosted documentation, python elements are not hyperlinked. For autodoc module to work, it needs to import the modules which are referenced. Could you update RTFD to install pylxd in the advanced settings please ? Then, references to python classes/methods/attrs/etc will link to the corresponding section in the api page.

![2016-05-23-203834_865x254_scrot](https://cloud.githubusercontent.com/assets/94636/15480604/bd037e14-2126-11e6-9d19-9fceec1981e1.png)

**Comment by rockstar** [comment]
RTD is now installing pylxd as part of its build process.

**Comment by jpic** [comment]
Is it installing this version ? Apparently autodoc still can't import it: links are not clickable.

**Comment by jpic** [comment]
Apparently it [fails because of openssl](http://readthedocs.org/projects/pylxd/builds/4033525/), can we install it too ?

```
 python /home/docs/checkouts/readthedocs.org/user_builds/pylxd/envs/latest/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=en . _build/epub
Running Sphinx v1.3.5
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 5 source files that are out of date
updating environment: 5 added, 0 changed, 0 removed
reading sources... [ 20%] api
reading sources... [ 40%] contributing
reading sources... [ 60%] index
reading sources... [ 80%] installation
reading sources... [100%] usage

/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/doc/source/api.rst:8: WARNING: autodoc: failed to import class u'Client' from module u'pylxd.client'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/__init__.py", line 19, in <module>
    from pylxd.deprecated import api  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/api.py", line 17, in <module>
    from pylxd.deprecated import certificate
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/certificate.py", line 17, in <module>
    from pylxd.deprecated import base
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/base.py", line 16, in <module>
    from pylxd.deprecated import connection
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/connection.py", line 40, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL
/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/doc/source/api.rst:14: WARNING: autodoc: failed to import class u'Container' from module u'pylxd.container'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/__init__.py", line 19, in <module>
    from pylxd.deprecated import api  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/api.py", line 17, in <module>
    from pylxd.deprecated import certificate
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/certificate.py", line 17, in <module>
    from pylxd.deprecated import base
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/base.py", line 16, in <module>
    from pylxd.deprecated import connection
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/connection.py", line 40, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL
/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/doc/source/api.rst:20: WARNING: autodoc: failed to import class u'Image' from module u'pylxd.image'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/__init__.py", line 19, in <module>
    from pylxd.deprecated import api  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/api.py", line 17, in <module>
    from pylxd.deprecated import certificate
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/certificate.py", line 17, in <module>
    from pylxd.deprecated import base
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/base.py", line 16, in <module>
    from pylxd.deprecated import connection
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/connection.py", line 40, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL
/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/doc/source/api.rst:26: WARNING: autodoc: failed to import class u'Operation' from module u'pylxd.operation'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/__init__.py", line 19, in <module>
    from pylxd.deprecated import api  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/api.py", line 17, in <module>
    from pylxd.deprecated import certificate
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/certificate.py", line 17, in <module>
    from pylxd.deprecated import base
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/base.py", line 16, in <module>
    from pylxd.deprecated import connection
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/connection.py", line 40, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL
/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/doc/source/api.rst:32: WARNING: autodoc: failed to import class u'Profile' from module u'pylxd.profile'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/__init__.py", line 19, in <module>
    from pylxd.deprecated import api  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/api.py", line 17, in <module>
    from pylxd.deprecated import certificate
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/certificate.py", line 17, in <module>
    from pylxd.deprecated import base
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/base.py", line 16, in <module>
    from pylxd.deprecated import connection
  File "/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/pylxd/deprecated/connection.py", line 40, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL
/home/docs/checkouts/readthedocs.org/user_builds/pylxd/checkouts/latest/doc/source/index.rst:11: WARNING: toctree contains reference to nonexisting document u'readme'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 20%] api
writing output... [ 40%] contributing
writing output... [ 60%] index
writing output... [ 80%] installation
writing output... [100%] usage

generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
done
copying extra files... done
writing mimetype file...
writing META-INF/container.xml file...
writing content.opf file...
writing toc.ncx file...
writing pylxd.epub file...
build succeeded, 7 warnings.
Command time: 1s Return: 0
```
